export {
  CALC_GEN,
  VGC_LEVEL,
  computeDamage,
  computeDamageForCombinedRange,
  computeDamageForDefenderRange,
  computeDamageForStatRange,
  defaultDefenderDefRange,
  defaultDefenderHpRange,
  defaultOffenseStatRange,
  defaultStatRange,
  getAttackStat,
  getAttackStatBounds,
  getDefenderDefBounds,
  getDefenderDefStat,
  getDefenderHp,
  getDefenderHpBounds,
  getOffenseStat,
  getOffenseStatBounds,
  nearestDefenderSetupForValues,
  nearestOffenseSetupForStat,
  snapToAchievableDefenseValues,
  snapToAchievableOffenseStat,
  warmDefenderSpreadCache,
  defenderDefRangeFromPresets,
  defenderHpRangeFromPresets,
  offenseRangeFromPresets,
  clampStat,
  sameStatRange,
  snapToAnchors,
} from "./compute-damage"
export {
  defenseSetupForTemplate,
  defenderDefRangeFromTemplates,
  defenderHpRangeFromTemplates,
  defenderStatsForTemplate,
  envelopeRange,
  offenseRangeFromTemplates,
  offenseSetupForTemplate,
  offenseStatForTemplate,
} from "./template-range"
export type {
  AttackStatBounds,
  ComputedDamage,
  DefenderSetup,
  KoProbabilities,
  KoProbabilityRange,
  KoProbabilityValue,
  ProbabilityMode,
  StatAxisBounds,
  StatAxisSnapPoint,
  StatRange,
  StatSetup,
} from "./types"

export {
  ATTACKER_ITEM_NAMES,
  ATTACKER_STAT_SETUPS,
  DEFENDER_SETUPS,
  getAttackerStatSetups,
  getDefenderSetups,
  offenseStatKey,
  defenseStatKey,
} from "./presets"
